services:
  - type: web
    name: drop-down-store
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false # User will provide this in the dashboard if the blueprint fails
