services:
  - type: web
    name: drop-web
    env: docker
    region: oregon
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: drop.settings
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: drop-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: drop-redis
          property: connectionString
      - fromGroup: drop-secrets

  - type: worker
    name: drop-worker
    env: docker
    region: oregon
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    startCommand: "celery -A drop worker -l info"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: drop.settings
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: drop-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: drop-redis
          property: connectionString
      - fromGroup: drop-secrets

databases:
  - name: drop-db
    plan: free
    region: oregon

redis:
  - name: drop-redis
    plan: free
    region: oregon

envVarGroups:
  - name: drop-secrets
    envVars:
      - key: SECRET_KEY
      - key: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
      - key: PAYSTACK_SECRET_KEY
      - key: ADMIN_EMAIL
      - key: SITE_URL
      - key: EMAIL_HOST_USER
      - key: EMAIL_HOST_PASSWORD
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET
