# Generated by Django 5.2.7 on 2026-01-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
    ]
