# Generated by Django 5.2.7 on 2026-01-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_brand_order_complete_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Collections', 'Collections')], max_length=100, null=True),
        ),
    ]
