# Generated by Django 5.2.7 on 2026-01-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_shoe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('id', 'id'), ('Male', 'Male'), ('Female', 'Female'), ('Collections', 'Collections')], max_length=100, null=True),
        ),
    ]
