# Generated by Django 5.2.7 on 2026-01-24 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_shoe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
