# Generated by Django 5.2.7 on 2026-01-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('id', ''), ('Male', 'Male'), ('Female', 'Female'), ('Collections', 'Collections')], max_length=100, null=True),
        ),
    ]
