# Generated by Django 5.2.7 on 2026-01-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_delete_brand_shoe_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('id', ''), ('Male', 'Male'), ('Female', 'Female'), ('Collections', 'Collections')], max_length=100),
        ),
    ]
