# Generated by Django 5.2.7 on 2026-01-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_shoe_brand_shoe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='name',
        ),
    ]
