# Generated by Django 5.2.7 on 2026-01-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_remove_shoe_brand_remove_shoe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
