# Generated by Django 5.2.7 on 2026-01-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_shoe_brand_shoe_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=100)),
                ('image', models.ImageField(upload_to='watchs/')),
                ('brand', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchs', to='web.category')),
            ],
        ),
    ]
