# Generated by Django 5.2.7 on 2026-01-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
