# Generated by Django 6.0.2 on 2026-03-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_order_status_shoe_description_shoe_discount_price_and_more'),
    ]

    operations = [
    ]
