# Generated by Django 6.0.2 on 2026-03-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
