# Generated by Django 6.0.2 on 2026-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_account_number',
            field=models.CharField(blank=True, help_text='Account number user confirmed they paid to', max_length=20, null=True),
        ),
    ]
