# Generated by Django 6.0.2 on 2026-03-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_order_confirmed_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Bank Transfer', max_length=50),
        ),
    ]
