# Generated by Django 6.0.2 on 2026-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Stock', 'Stock Purchase'), ('Utility', 'Utility Bill'), ('Rent', 'Rent'), ('Staff', 'Staff Salary'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='Other', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='shoe',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='What you paid for the item', max_digits=10),
        ),
        migrations.AddField(
            model_name='watch',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='What you paid for the item', max_digits=10),
        ),
    ]
